### ISSUE TITLE
Suggestion (not issue): Interface with backboneORM library

### ISSUE THREAD

**Issue by brucou** [scttnlsn/data.io#7]
I love the idea of having small modules who do one thing and one thing well, as it seems to be the idea here, specially as there is plenty of existing library revolving around REST apis on HTTP while the equivalent with socket transport is not existing.
How hard would it be to mix in backboneORM functionality with data.io socket transport? 
The combination of the two would cover so many use cases.

**Comment by scttnlsn** [comment]
I'm sure it's very possible.  I extracted `data.io` out of another project (https://github.com/scttnlsn/backbone.io) with the goal of keeping the APIs low-level enough that one could plug it into a higher level abstraction (such as backboneORM) if desired.  I'm not familiar with backboneORM and have no intention of including that integration as part of the core library but please open any issues you encounter when trying to integrate the two.
